# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Setup MySQL
      run: |
        sudo /etc/init.d/mysql start
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test -v n --logger "trx;LogFileName=test-results.trx"
      env:
        Database__ConnectionString: "server=localhost;user=root;password=root;database=plm_ssp_testing"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: xUnit Tests            # Name of the check run which will be created
        path: test-results.trx   # Path to test results
        reporter: dotnet-trx
